name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-nginx:
    name: Build nginx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pldin601/musicloud-nginx
          tags: latest
          dockerfile: docker/nginx/Dockerfile
  build-php-fpm:
    name: Build php-fpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pldin601/musicloud-php-fpm
          tags: latest
          dockerfile: docker/php-fpm/Dockerfile
  build-migration:
    name: Build migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pldin601/musicloud-migration
          tags: latest
          dockerfile: docker/migration/Dockerfile
